### ISSUE TITLE
When lighthouse cannot reach site, lighthouse-ci reports all tests passing

### ISSUE THREAD

**Issue by glassdimly** [andreasonny83/lighthouse-ci#56] opened 2019-10-16 20:36 UTC
**What happens**
Here's what `lighthouse-ci` generates:
![image](https://user-images.githubusercontent.com/1361104/66956605-49dca380-f02a-11e9-833b-8eea3e732c58.png)

Here's what `lighthouse` cli generates from the same site.
```
lighthouse http://local.mysite.org
  ...
Runtime error encountered: Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 503)
```
**What should happen**
If `lighthouse` returns a `503`, `lighthouse-ci` should report a fail, or fail all tests.

**Comment by andreasonny83** [comment] 2020-01-12 15:45
First of all, thanks for your help @glassdimly

To be honest, that doesn't really sound like a bug to me.
The problem is that, when providing an invalid URL to Chrome, the page is still rendering something depending on your Internet provider. You cannot see an error page directly in Chrome as it defaults to some content instead.

Also, checking the existence of the website could be generally done before running performance tests, via E2E tests or integrations.

Closing this issue for now. Please, feel free to reopen if you don't agree or you have more questions.

**Closed by andreasonny83** 2020-01-12 15:45 UTC
